### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [frankhefeng/xk6-oauth-pkce#1]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add the xk6 topic to your repository metadata
* add an `examples` directory containing k6 test scripts making use of your extension
* requires at least one versioned release

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by frankhefeng** [comment]
Updated as requested. Please have a look. Thanks

**Comment by javaducky** [comment]
@frankhefeng, thank you for looking this! One point of note however, the `example` directory should be `examples`.

We will be creating automation to verify things in the near future and this typo will cause issues going forward.

**Comment by frankhefeng** [comment]
Fixed, @javaducky
